apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: web-interface
      port: 7860
      targetPort: 7860
    - name: rest-api
      port: 8080
      targetPort: 8080
