apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
       app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - image: "leonpatmore2/wiki-search:{{ .Values.tag }}"
          name: {{ .Release.Name }}
          env:
            - name: OPENAI_API_KEY
              value: {{ .Values.openAiApiKey }}
            - name: SLACK_CHANNEL
              value: {{ .Values.slackChannel }}
            - name: SLACK_TOKEN
              value: {{ .Values.slackToken }}
          ports:
            - name: web-interface
              containerPort: 8080
            - name: rest-api
              containerPort: 8082
            - name: slack-listener
              containerPort: 8084
          volumeMounts:
            - mountPath: "/app/docs"
              name: docs
              readOnly: false
      volumes:
        - name: docs
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-docs
