apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-rest-api
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    kubernetes.io/ingress.class: ingress-controller-internal-nginx
spec:
  rules:
    - host: {{ .Values.restApiHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  number: 8082
